{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-file-server.fullname" . }}
  labels:
    {{- include "minio-file-server.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  host: {{ .Values.minio.host | toString | b64enc }}
  accessKey: {{ .Values.minio.accessKey | toString | b64enc }}
  secretKey: {{ .Values.minio.secretKey | toString | b64enc }}
  bucket: {{ .Values.minio.bucket | toString | b64enc }}
  use-ssl: {{ .Values.minio.SSL.enabled | toString | b64enc }}
{{- end }}
