apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio-file-server.fullname" . }}
  labels:
    {{- include "minio-file-server.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: io.safesurfer.minio-file-server
    {{- include "minio-file-server.selectorLabels" . | nindent 4 }}
